# Ejemplos de la sección 2.2 del libro "deep learning with python" (Chollet)

## Escalares o tensores 0D


In [2]:
import numpy as np
x0 = np.array(12)
print(x0)
print(x0.ndim)
print(x0.shape)

12
0
()


## Vectores o tensores 1D

Un vector es un tensor de dimensión 1.

El vector que creamos en la celda siguiente es un vector de dimensión 5, pero sigue siendo un tensor de dimensión 1. Así que no confundir un tensor nD con un vector nD; un vector nD siempre será un tensor 1D, sea cual sea n.

El tema es que la dimensionalidad de un tensor es el nº de ejes que tiene dicho tensor. Sería menos confuso y, probablemente más correcto utilizar la palabra "rango" de un tensor, pero lo habitual es hablar de su dimensión.

In [3]:
x1 = np.array([2,3,5,3,2])
print(x1)
print(x1.ndim)
print(x1.shape)

[2 3 5 3 2]
1
(5,)


## Matrices o tensores 2D

Una matriz es un tensor de dimensión o rango 2. Se trata de un array de vectores. Tiene, por tanto, dos ejes que se suelen denominar filas y columnas.

In [4]:
x2 = np.array([[4,5,6],[2,3,4]])
print(x2)
print(x2.ndim)
print(x2.shape)

[[4 5 6]
 [2 3 4]]
2
(2, 3)


## Tensores 3D y de dimensión mayor
Un tensor 3D tiene 3 ejes, que podemos llamar x, y, z. Se trata de empaquetar en un array tensores de dimensión 2. De la misma manera un tensor de dimensión N se construye empaquetando en un array tensores de dimensión N-1.

In [5]:
x3 = np.array([[[1,2,3], [4,3,2]], [[2,4,7], [3,4,6]]])
print(x3)
print(x3.ndim)
print(x3.shape)

[[[1 2 3]
  [4 3 2]]

 [[2 4 7]
  [3 4 6]]]
3
(2, 2, 3)


## Atributos de un tensor

In [6]:
# El rango o nº de ejes
print("El rango de x3 es {}".format(x3.ndim))
# La forma, que es una tupla que indica cuantos elementos tiene el tensor en cada eje
print("la forma de x3 es {}".format(x3.shape))
# El tipo de datos (dtype) es el tipo de datos que contiene el tensor
print("El tipo de datos de x3 es {}".format(x3.dtype))

El rango de x3 es 3
la forma de x3 es (2, 2, 3)
El tipo de datos de x3 es int64


## Ejemplos del dataset mnist

In [7]:
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

print("El rango de train_images es {}".format(train_images.ndim))
# La forma, que es una tupla que indica cuantos elementos tiene el tensor en cada eje
print("la forma de train_images es {}".format(train_images.shape))
# El tipo de datos (dtype) es el tipo de datos que contiene el tensor
print("El tipo de datos de train_images es {}".format(train_images.dtype))

print("El rango de train_labels es {}".format(train_labels.ndim))
# La forma, que es una tupla que indica cuantos elementos tiene el tensor en cada eje
print("la forma de train_labels es {}".format(train_labels.shape))
# El tipo de datos (dtype) es el tipo de datos que contiene el tensor
print("El tipo de datos de train_labels es {}".format(train_labels.dtype))

Using TensorFlow backend.


El rango de train_images es 3
la forma de train_images es (60000, 28, 28)
El tipo de datos de train_images es uint8
El rango de train_labels es 1
la forma de train_labels es (60000,)
El tipo de datos de train_labels es uint8


## Mostrando graficamente los datos de entrada

In [8]:
digit = train_images[7]
import matplotlib.pyplot as plt

plt.imshow(digit, cmap=plt.cm.binary)
plt.show()

<Figure size 640x480 with 1 Axes>

## Manipulando tensores

In [9]:
# tensor slicing

train_images[0:10]
train_images[0:10, :, :]
train_images[:, 0:14, :][1]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,  51, 159, 253, 159,  50,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  48, 238, 252, 252, 252, 237,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

## Data batches
En deep learning el primer eje del tensor, es decir el eje 0, es el denominado eje de muestras, ya que cada elemento a lo largo de ese eje representa una muestra (dato de entrada) del conjunto de entrenamiento o test.

Además los modelos de deep-learning no procesan todas las muestras del tirón, sino que dividen los datos en lotes (batches). Por ejemplo de 128 muestras.

Al eje 0 se le suele llamar *batch axis* o *batch dimension*

In [10]:
batch0 = train_images[0: 128]
batch1 = train_images[128: 256]

def batch(data, batch_size, n):
    return data[batch_size * n : batch_size * (n - 1) ]

batch4 = batch(train_images, 128, 4)

## Tensores típicos para deep learning

Los tensores más típicos son los 2D, en el eje 0 se representa la muestra y en el eje 1 los atributos. Por ejemplo 100000 textos representados como un vector en el que cada elemento representa una palabra de un diccionario. Si el diccionario tiene 2000 palabras, el tensor que representa dichos datos tendría una forma (100000, 2000).

Con los tensores 3D se suelen representar series de datos, normalmente temporales. Por ejemplo los valores de temperatura, presión y humedad registrados por una estación meteorológica cada minuto siendo cada día una muestra. Si queremos representar con un tensor los datos recogidos en 30 días, la forma de dicho tensor sería (30, 1440, 3), es decir 30 muestras en las que se registran 3 valores de los sensores (temperatura, presión y humedad) durante 1440 segundos.

Con tensores 3D también podemos representar conjuntos de imágenes en escala de grises. Por ejemplo para representar un conjunto de 10000 imágenes con una resolución de 1240 x 720 necesitamos un tensor de forma (10000, 1240, 720).

Si la imagen es en color, necesitamos también la información del canal (R, G, B), así para el mismo caso anterior pero en color, necesitamos un tensor de forma (10000, 1240, 720, 3).

Por último las muestras de vídeos requieren tensores de 5 dimensiones para representarlas, ya que un vídeo consta de un conjunto de imágenes. Por ejemplo para representar un conjunto de 4 vídeos siendo cada uno de ellos de una resolución de 144 x 256, en color, con una duración de 60 segundos y sampleados a 4 imágenes por segundo necesitamos un tensor de forma (4, 240, 144, 256, 3).

# Operaciones con tensores

## Operaciones elemento a elemento (element-wise)

In [25]:
x = np.array([[3, 5, 3], [2,1,5]])
y = np.array([[4,7,6], [2,6,7]])
z = np.array([1,2,3])
print(x + y)
print(x * y)
print(x + z)

[[ 7 12  9]
 [ 4  7 12]]
[[12 35 18]
 [ 4  6 35]]
[[4 7 6]
 [3 3 8]]


## Producto escalar (tensor dot)

In [30]:
t = np.array([[2,6], [2,7], [5, 7]])
print(np.dot(x,z))
print(np.dot(x,t))


[22 19]
[[31 74]
 [31 54]]


## Reshaping

In [37]:
k = x.reshape(6,1)
print(k)
print(x)
print(x.transpose())

[[3]
 [5]
 [3]
 [2]
 [1]
 [5]]
[[3 5 3]
 [2 1 5]]
[[3 2]
 [5 1]
 [3 5]]
